# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aguardando_ciente_date', models.DateTimeField(blank=True, null=True, verbose_name='data aguardando ciente')),
                ('aguardando_inspecao_date', models.DateTimeField(blank=True, null=True, verbose_name='data aguardando inspecao')),
                ('realizando_inspecao_date', models.DateTimeField(blank=True, null=True, verbose_name='data realizando inspecao')),
                ('aguardando_manutencao_date', models.DateTimeField(blank=True, null=True, verbose_name='data aguardando manutencao')),
                ('em_manutencao_date', models.DateTimeField(blank=True, null=True, verbose_name='data em manutencao')),
                ('aguardando_testes_date', models.DateTimeField(blank=True, null=True, verbose_name='data aguardando testes')),
                ('testes_em_execucao_date', models.DateTimeField(blank=True, null=True, verbose_name='data testes em execucao')),
                ('remanutencao_date', models.DateTimeField(blank=True, null=True, verbose_name='data remanutencao')),
                ('aguardando_remessa_date', models.DateTimeField(blank=True, null=True, verbose_name='data aguardando remessa')),
                ('fechada_sem_ciente_date', models.DateTimeField(blank=True, null=True, verbose_name='data fechada sem ciente')),
                ('fechada_arquivar_date', models.DateTimeField(blank=True, null=True, verbose_name='data fechada arquivar')),
                ('realizacao_date', models.DateTimeField(blank=True, null=True, verbose_name='data realizacao')),
                ('tipo', models.IntegerField(choices=[(0, 'Apoio em conjunto'), (1, 'Apoio direto'), (2, 'Apoio em suprimento')])),
                ('status', models.IntegerField()),
                ('nd', models.IntegerField()),
                ('pit', models.BooleanField()),
                ('tempo', models.IntegerField(null=True)),
                ('suprimento_aplicado', models.TextField(blank=True)),
                ('motivo', models.CharField(max_length=255)),
                ('desc_material', models.TextField(blank=True)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('serv_realizado', models.TextField(blank=True)),
                ('custo_total', models.IntegerField()),
                ('classe', models.IntegerField()),
                ('om_requerente', models.CharField(blank=True, max_length=255)),
                ('ordem_recolhimento', models.CharField(blank=True, max_length=30)),
                ('guia_recolhimento', models.CharField(blank=True, max_length=30)),
                ('num_diex', models.CharField(blank=True, max_length=30)),
                ('medidas_corretivas', models.TextField(blank=True)),
                ('quant_homens', models.IntegerField(blank=True, default=0)),
                ('prestador_servico', models.CharField(blank=True, max_length=255)),
                ('ch_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ch_Classe', to='login.InformacaoMilitar')),
                ('ch_cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ch_CP', to='login.InformacaoMilitar')),
                ('cmt_pel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cmt_Pel', to='login.InformacaoMilitar')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('classe', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'), (11, 'XI'), (12, 'XII')])),
            ],
        ),
        migrations.CreateModel(
            name='Subsistemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('classe', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'), (11, 'XI'), (12, 'XII')])),
            ],
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.Sistema'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='subsistemas_manutenidos',
            field=models.ManyToManyField(to='ordemDeServico.Subsistemas'),
        ),
    ]
